name: CI (smoke build)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ===== API: .NET 9.0, один проект =====
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          cache: true
          cache-dependency-path: api/TelegramBlock.csproj

      - name: Restore API
        run: dotnet restore api/TelegramBlock.csproj

      - name: Build API
        run: dotnet build api/TelegramBlock.csproj -c Release --no-restore

      # ===== UI: Vite, без lock-файла =====
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Если есть ui/.env.example — используем его как .env.
      - name: Prepare UI .env
        working-directory: ui
        run: |
          if [ -f ".env.example" ]; then
            cp .env.example .env
          else
            printf "VITE_API_BASE_URL=\nVITE_API_PREFIX=/api\n" > .env
          fi
          echo "Created UI .env:"
          cat .env

      - name: Install UI deps
        working-directory: ui
        run: npm install

      - name: Build UI
        working-directory: ui
        run: npm run build
